add checks for date command

diff --git a/dt b/dt
--- a/dt
+++ b/dt
@@ -1,3 +1,10 @@
 #!/bin/sh
 
-exec date "+%n  YEAR: %Y%n MONTH: %m (%B)%n   DAY: %d (%A)%n  TIME: %r%n"
+set -e
+
+if ! command="$(command -p -v date)"; then
+    printf "%s: command not found -- date\n" "${0##*/}" 1>&2
+    exit 1
+fi
+
+exec "$command" "+%n  YEAR: %Y%n MONTH: %m (%B)%n   DAY: %d (%A)%n  TIME: %r%n"
