remove `error' function, use full path to executables

diff --git a/rn b/rn
--- a/rn
+++ b/rn
@@ -3,26 +3,37 @@
 
 set -e
 
-error () { printf "%s: %s\n" "${0##*/}" "$1" >&2; exit 1; }
+if ! move_files="$(command -p -v mv)"; then
+    printf "%s: command not found -- mv\n" "${0##*/}" 1>&2
+    exit 1
+elif ! make_directories="$(command -p -v mkdir)"; then
+    printf "%s: command not found -- mkdir\n" "${0##*/}" 1>&2
+    exit 1
+fi
 
-case $# in
-    0)
-        exec "$0" *
-        ;;
-    1)
-        [ \* = "$1" -a ! -e \* ] && error "current directory is empty"
-        [ -e "$1" ] || error "$1: no such file or directory"
-        ;;
-    *)
-        for pathname in "$@"; do
-            [ -e "$pathname" ] || error "$pathname: no such file or directory"
-        done
-esac
+if [ $# -eq 0 ]; then
+    exec "$0" *
+elif [ $# -eq 1 ]; then
+    if [ \* = "$1" -a ! -e \* ]; then
+        printf "%s: current directory is empty\n" "${0##*/}" 1>&2
+        exit 1
+    elif [ ! -e "$1" ]; then
+        printf "%s: no such file or directory -- %s\n" "${0##*/}" "$1" 1>&2
+        exit 1
+    fi
+else
+    for pathname in "$@"; do
+        if [ ! -e "$pathname" ]; then
+            printf "%s: no such file or directory -- %s\n" "${0##*/}" "$pathname" 1>&2
+            exit 1
+        fi
+    done
+fi
 
 IFS=' '
 case "$*" in
     *'
-'*) error "argument(s) contains a newline" ;;
+'*) printf "%s: argument(s) contains a newline\n" "${0##*/}" 1>&2; exit 1 ;;
 esac
 
 pathnames="${TMPDIR:-/tmp}/${0##*/}.$$"
@@ -36,7 +47,10 @@ while read -r output; do
     pathnames_out="$(($pathnames_out + 1))"
 done < "$pathnames"
 
-[ "$pathnames_in" -eq "$pathnames_out" ] || error "added/deleted lines"
+if [ "$pathnames_in" -ne "$pathnames_out" ]; then
+    printf "%s: added/deleted lines\n" "${0##*/}" 1>&2
+    exit 1
+fi
 
 renamed_pathnames=0
 while read -r output; do
@@ -47,13 +61,16 @@ while read -r output; do
     shift 1
 done < "$pathnames"
 
-[ "$renamed_pathnames" -ne 0 ] || error "no filenames were changed"
+if [ "$renamed_pathnames" -eq 0 ]; then
+    printf "%s: no filenames were changed\n" "${0##*/}" 1>&2
+    exit 1
+fi
 
 until [ $# -eq 0 ]; do
     case "$2" in
-        */*) [ -d "${2%/*}" ] || mkdir -p "${2%/*}" ;;
+        */*) [ -d "${2%/*}" ] || "$make_directories" -p -- "${2%/*}" ;;
     esac
-    mv -- "$1" "$2"
+    "$move_files" -- "$1" "$2"
     shift 2
 done
 
