update

diff --git a/trim-video b/trim-video
--- a/trim-video
+++ b/trim-video
@@ -1,191 +1,185 @@
 #!/bin/sh
 
-readonly PROGRAM="${0##*/}" SPACE=' ' TAB='	' NL='
-'
-readonly DEFAULT_IFS="${SPACE}${TAB}${NL}"
+error () { printf "${0##*/}: %s\n" "$*" >&2; exit 1; }
 
-IFS="$DEFAULT_IFS"
-
-Error() { printf "$@" >&2; exit 1; }
-
-input_file=
-start_position=
-end_position=
-rotate_video=
-assume_yes=
-while getopts ':i:s:t:r:y' user_input
-do
-	case "$user_input" in
-		(i) input_file="${OPTARG:-NULL}" ;;
-		(s) start_position="${OPTARG:-NULL}";;
-		(t) end_position="${OPTARG:-NULL}";;
-		(r) rotate_video="${OPTARG:-NULL}" ;;
-		(y) assume_yes="true" ;;
-		(:) Error '%s: option requires an argument -- %c\n' "$PROGRAM" "$OPTARG" ;;
-		(\?) Error '%s: illegal argument -- %c\n' "$PROGRAM" "$OPTARG" ;;
-	esac
+unset INPUT_FILE START END ROTATE ASSUME_YES
+while getopts :i:s:t:r:y OPTION; do
+    case "$OPTION" in
+        (i) INPUT_FILE="${OPTARG:-NULL}" ;;
+        (s) START="${OPTARG:-NULL}";;
+        (t) END="${OPTARG:-NULL}";;
+        (r) ROTATE="${OPTARG:-NULL}" ;;
+        (y) ASSUME_YES="true" ;;
+        (:) error "option requires an argument -- $OPTARG" ;;
+        (?) error "illegal argument -- $OPTARG" ;;
+    esac
 done
 shift $((OPTIND - 1))
 
-case $# in
-	(0)
-		output_directory="$(pwd)"
-		;;
-	(1)
-		test -n "$1" || Error '%s: directory operand cannot be a empty string\n' "$PROGRAM"
-		test -d "$1" || Error '%s: directory does not exist or is not a directory\n' "$PROGRAM"
+CWD="$(pwd)"
 
-		output_directory="$(cd "$1" 2> /dev/null && pwd)" \
-			|| Error '%s: permission denied for specified directory\n' "$PROGRAM"
-		;;
-	(*)
-		Error '%s: too many directory operands\n' "$PROGRAM"
-		;;
-
-esac
-
-output_directory="${output_directory%/}"
-
-test -n "$input_file" || Error '%s: missing file argument\n' "$PROGRAM"
-test "$input_file" != "NULL" || Error '%s: file argument cannot be a empty string\n' "$PROGRAM"
-test -f "$input_file" || Error '%s: file operand does not exist or is not a regular file\n' "$PROGRAM"
-
-case "$input_file" in
-	(/*) ;;
-	(./*) input_file="$(pwd)/${input_file#*\./}" ;;
-	(*) input_file="$(pwd)/${input_file}" ;;
-esac
-
-if test "${input_file%/*}" = "$output_directory"; then
-	Error '%s: input and output can not be in the same dirctory\n' "$PROGRAM"
-fi
-
-input_directory="${input_file%/*}" input_file="${input_file##*/}"
-
-case "$input_file" in
-	(VID_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9][0-9].mp4) ;;
-	(*) Error '%s: invalid file operand\n' "$PROGRAM" ;;
-esac
-
-file_date_time=${input_file}
-file_date_time=${file_date_time#VID_}
-file_date_time=${file_date_time%.mp4}
-file_date=${file_date_time%_*} file_time=${file_date_time#*_}
-
-year=${file_date%????} month=${file_date#????} day=${file_date#??????}; month=${month%??}
-hour=${file_time%????} minute=${file_time#??} second=${file_time#????}; minute=${minute%??}
-
-month=${month#0} day=${day#0} hour=${hour#0} minute=${minute#0} second=${second#0}
-
-case "$rotate_video" in
-	('') unset rotate_video ;;
-	(NULL) rotate_video= ;;
-	([0-9]|[1-9][0-9]|[12][0-9][0-9]|3[0-5][0-9]|360) ;;
-	(*) Error '%s: invalid rotation operand\n' "$PROGRAM" ;;
-esac
-
-case "$start_position" in
-	('')
-		unset start_position start_display
-		;;
-	([0-9]|[0-9][0-9]|[0-9][0-9]:[0-9][0-9])
-		IFS=:; set -- $start_position
-		IFS="$DEFAULT_IFS"
-
-		case $# in
-			(1)
-				start_minute=0 start_second="$1"
-				start_second="${start_second#0}"
-				;;
-			(2)
-				start_minute="$1" start_second="$2"
-				start_minute="${start_minute#0}" start_second="${start_second#0}"
-				;;
-		esac
-
-		start_minute="$((start_minute * 60))"
-		start_time="$((start_minute + start_second))"
-		second="$((second + start_time))"
-
-		until test $second -lt 60; do second="$((second - 60))" minute="$((minute + 1))"; done
-		until test $minute -lt 60; do minute="$((minute - 60))" hour="$((hour + 1))"; done
-		until test $hour -lt 24; do hour="$((hour - 24))" day="$((day + 1))"; done
-
-		case "$start_position" in
-			([0-9]|[0-9][0-9]) start_display="${start_position}s" ;;
-			([0-9][0-9]:[0-9][0-9]) start_display="${start_position}" ;;
-		esac
-		;;
-	(*)
-		Error '%s: invalid start argument (hint: <MM>:<SS> or <SS>)\n' "$PROGRAM"
-		;;
-esac
-
-case "$end_position" in
-	('')
-		unset end_position duration_time end_display
-		;;
-	([0-9]|[0-9][0-9]|[0-9][0-9]:[0-9][0-9])
-		IFS=:; set -- $end_position
-		IFS="$DEFAULT_IFS"
-
-		case $# in
-			(1)
-				end_minute=0 end_second="$1"
-				end_second="${end_second#0}"
-				;;
-			(2)
-				end_minute="$1" end_second="$2"
-				end_minute="${end_minute#0}" end_second="${end_second#0}"
-				;;
-		esac
-
-
-		end_minute="$((end_minute * 60))"
-		duration_time="$((end_minute + end_second - ${start_time:-0}))"
-
-		case "$end_position" in
-			([0-9]|[0-9][0-9]) end_display="${end_position}s" ;;
-			([0-9][0-9]:[0-9][0-9]) end_display="${end_position}" ;;
-		esac
-		;;
-	(*)
-		Error '%s: invalid end argument (hint: <MM>:<SS> or <SS>)\n' "$PROGRAM"
-		;;
-esac
-
-case "$month" in ([0-9]) month="0${month}" ;; esac
-case "$day" in ([0-9]) day="0${day}" ;; esac
-case "$hour" in ([0-9]) hour="0${hour}" ;; esac
-case "$minute" in ([0-9]) minute="0${minute}" ;; esac
-case "$second" in ([0-9]) second="0${second}" ;; esac
-
-input_file="$input_directory/$input_file"
-output_file="${output_directory%/}/VID_${year}${month}${day}_${hour}${minute}${second}.mp4"
-
-printf '\n%8s: %s' "Input" "$input_file" "Output" "$output_file"
-
-if test -n "$start_display" && test -n "$end_display"; then
-	printf '\n%8s: %-10s%s: %s (%ss)\n\n' "Start" "$start_display" "End" "$end_display" "$duration_time"
-elif test -n "$start_display"; then
-	printf '\n%8s: %s\n\n' "Start" "$start_display"
-elif test -n "$end_display"; then
-	printf '\n%8s: %s\n\n' "End" "$end_display"
+if [ -z "$INPUT_FILE" ]; then
+    error "missing file argument"
+elif [ ! -f "$INPUT_FILE" ]; then
+    error "\"$INPUT_FILE\" does not exist or is not a regular file"
+elif [ ! -r "$INPUT_FILE" ]; then
+    error "unable to read \"$INPUT_FILE\" file"
 else
-	printf '\n\n'
+    case "$INPUT_FILE" in
+        (/*) ;;
+        (./*) INPUT_FILE="$CWD/${INPUT_FILE#*\./}" ;;
+        (*) INPUT_FILE="$CWD/${INPUT_FILE}" ;;
+    esac
 fi
 
-set -- ffmpeg \
-	-loglevel warning -stats \
-	${assume_yes:+-y} -i "$input_file" \
-	${start_position:+-ss $start_position} \
-	${end_position:+-to $end_position} \
-	-c copy -map_metadata -1  \
-	${rotate_video+-metadata:s:v rotate=$rotate_video} \
-	-async 1 "$output_file"
+case $# in
+    (0)
+        [ -w "$CWD" ] || error "permission denied for current directory"
+        OUTPUT_DIR="$CWD"
+        ;;
+    (1)
+        [ -n "$1" ] || error "directory operand cannot be a empty string"
+        [ -d "$1" ] || error "directory does not exist or is not a directory"
+        [ -w "$1" ] || error "permission denied for specified directory"
+        OUTPUT_DIR="$(cd "$1" 2> /dev/null && pwd)" || exit
+        ;;
+    (*)
+        error "too many directory operands"
+        ;;
+esac
 
-test -n "$assume_yes" && exec "$@"
+if [ "${INPUT_FILE%/*}" = "$OUTPUT_DIR" ]; then
+    error "input and output can not be in the same dirctory"
+fi
 
-printf 'Do you want to run command? [Y/n]: ' >&2
-read -r user_input
-case "$user_input" in (''|[Yy]|[Yy][Ee][Ss]) exec "$@" ;; esac
+INPUT_DIR="${INPUT_FILE%/*}" INPUT_FILE="${INPUT_FILE##*/}"
+
+case "$INPUT_FILE" in
+    (VID_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9][0-9].mp4) ;;
+    (*) error "invalid file operand" ;;
+esac
+
+PREFIX="$INPUT_FILE"            PREFIX="${PREFIX%%_*}_" DELETE="${PREFIX}"           \
+YEAR="${INPUT_FILE#$DELETE}"    YEAR="${YEAR%????_*}"   DELETE="${DELETE}${YEAR}"    \
+MONTH="${INPUT_FILE#$DELETE}"   MONTH="${MONTH%??_*}"   DELETE="${DELETE}${MONTH}"   \
+DAY="${INPUT_FILE#$DELETE}"     DAY="${DAY%_*}"         DELETE="${DELETE}${DAY}_"    \
+HOUR="${INPUT_FILE#$DELETE}"    HOUR="${HOUR%????.*}"   DELETE="${DELETE}${HOUR}"    \
+MINUTE="${INPUT_FILE#$DELETE}"  MINUTE="${MINUTE%??.*}" DELETE="${DELETE}${MINUTE}"  \
+SECOND="${INPUT_FILE#$DELETE}"  SECOND="${SECOND%.*}"   DELETE="${DELETE}${SECOND}"  \
+SUFFIX="${INPUT_FILE#$DELETE}"
+
+case "$MONTH"  in (0[0-9]) MONTH="${MONTH#0}"   ;; esac
+case "$DAY"    in (0[0-9]) DAY="${DAY#0}"       ;; esac
+case "$HOUR"   in (0[0-9]) HOUR="${HOUR#0}"     ;; esac
+case "$MINUTE" in (0[0-9]) MINUTE="${MINUTE#0}" ;; esac
+case "$SECOND" in (0[0-9]) SECOND="${SECOND#0}" ;; esac
+
+if [ -n "$ROTATE" ]; then
+    case "$ROTATE" in
+        ([0-9]|[1-9][0-9]|[12][0-9][0-9]|3[0-5][0-9]|360)
+            ROTATE="-metadata:s:v rotate=$ROTATE"
+            ;;
+        (NULL)
+            ROTATE="-metadata:s:v rotate="
+            ;;
+        (*) error "invalid rotation operand"
+            ;;
+    esac
+else
+    unset ROTATE
+fi
+
+if [ -n "$START" ]; then
+    case "$START" in
+        ([0-9]|[0-9][0-9]|[0-9][0-9]:[0-9][0-9])
+            case "$START" in
+                (*:*) START_MINUTE="${START%:*}" START_SECOND="${START#*:}" ;;
+                (*)   START_MINUTE=0             START_SECOND="$START" ;;
+            esac
+
+            case "$START_MINUTE" in (0[0-9]) START_MINUTE="${START_MINUTE#0}" ;; esac
+            case "$START_SECOND" in (0[0-9]) START_SECOND="${START_SECOND#0}" ;; esac
+
+            START_MINUTE="$((START_MINUTE * 60))"
+            START_TIME="$((START_MINUTE + START_SECOND))"
+            SECOND="$((SECOND + START_TIME))"
+
+            until test $SECOND -lt 60; do SECOND="$((SECOND - 60))" MINUTE="$((MINUTE + 1))"; done
+            until test $MINUTE -lt 60; do MINUTE="$((MINUTE - 60))" HOUR="$((HOUR + 1))"; done
+            until test $HOUR -lt 24; do HOUR="$((HOUR - 24))" DAY="$((DAY + 1))"; done
+
+            case "$START" in
+                ([0-9]|[0-9][0-9]) START_DISPLY="${START}s" ;;
+                ([0-9][0-9]:[0-9][0-9]) START_DISPLY="${START}" ;;
+            esac
+            ;;
+        (*)
+            error "invalid start argument (hint: <MM>:<SS> or <SS>)"
+            ;;
+    esac
+    START="-ss $START"
+else
+    unset START START_DISPLY
+fi
+
+if [ -n "$END" ]; then
+    case "$END" in
+        ([0-9]|[0-9][0-9]|[0-9][0-9]:[0-9][0-9])
+            case "$END" in
+                (*:*) END_MINUTE="${END%:*}" END_SECOND="${END#*:}" ;;
+                (*)   END_MINUTE=0           END_SECOND="$END" ;;
+            esac
+
+            case "$END_MINUTE" in (0[0-9]) END_MINUTE="${END_MINUTE#0}" ;; esac
+            case "$END_SECOND" in (0[0-9]) END_SECOND="${END_SECOND#0}" ;; esac
+
+            DURATION_TIME="$(($((END_MINUTE * 60)) + END_SECOND - ${START_TIME:-0}))"
+
+            case "$END" in
+                ([0-9]|[0-9][0-9]) END_DISPLAY="${END}s" ;;
+                ([0-9][0-9]:[0-9][0-9]) END_DISPLAY="${END}" ;;
+            esac
+            ;;
+        (*)
+            error "invalid end argument (hint: <MM>:<SS> or <SS>)"
+            ;;
+    esac
+    END="-to $END"
+else
+    unset END DURATION_TIME END_DISPLAY
+fi
+
+case "$MONTH"  in ([0-9]) MONTH="0${MONTH}"   ;; esac
+case "$DAY"    in ([0-9]) DAY="0${DAY}"       ;; esac
+case "$HOUR"   in ([0-9]) HOUR="0${HOUR}"     ;; esac
+case "$MINUTE" in ([0-9]) MINUTE="0${MINUTE}" ;; esac
+case "$SECOND" in ([0-9]) SECOND="0${SECOND}" ;; esac
+
+INPUT_FILE="$INPUT_DIR/$INPUT_FILE"
+OUTPUT_FILE="$OUTPUT_DIR/${PREFIX}${YEAR}${MONTH}${DAY}_${HOUR}${MINUTE}${SECOND}${SUFFIX}"
+
+if [ -n "$START_DISPLY" -a -n "$END_DISPLAY" ]; then
+    printf "\n%8s: %s\n%8s: %s\n%8s: %-10s%s: %s (%ss)\n\n" \
+        Input "$INPUT_FILE" Output "$OUTPUT_FILE" Start "$START_DISPLY" End "$END_DISPLAY" "$DURATION_TIME"
+elif [ -n "$START_DISPLY" ]; then
+    printf "\n%8s: %s\n%8s: %s\n%8s: %s\n\n" \
+        Input "$INPUT_FILE" Output "$OUTPUT_FILE" Start "$START_DISPLY"
+elif [ -n "$END_DISPLAY" ]; then
+    printf "\n%8s: %s\n%8s: %s\n%8s: %s\n\n" \
+        Input "$INPUT_FILE" Output "$OUTPUT_FILE" End "$END_DISPLAY"
+else
+    printf "\n%8s: %s\n%8s: %s\n\n" \
+        Input "$INPUT_FILE" Output "$OUTPUT_FILE"
+fi
+
+INPUT_OPTIONS="-loglevel warning -stats"
+OUTPUT_OPTIONS="$START $END -c copy -map_metadata -1 $ROTATE -async 1"
+
+if [ -z "$ASSUME_YES" ]; then
+    printf 'Do you want to run command? [Y/n]: '
+    read -r OPTION
+    case "$OPTION" in (''|[Yy]|[Yy][Ee][Ss]) ;; (*) exit 0 ;; esac
+    exec ffmpeg $INPUT_OPTIONS -i "$INPUT_FILE" $OUTPUT_OPTIONS "$OUTPUT_FILE"
+else
+    exec ffmpeg -y $INPUT_OPTIONS -i "$INPUT_FILE" $OUTPUT_OPTIONS "$OUTPUT_FILE"
+fi
