remove `error' function

diff --git a/trm b/trm
--- a/trm
+++ b/trm
@@ -2,38 +2,49 @@
 
 set -e
 
-USAGE="Usage: %s -i VID_XXXXXXXX_XXXXXX.mp4 [-s [mm:]ss] [-t [mm:]ss] [-r rotation] [directory]"
+usage="Usage: %s -i VID_XXXXXXXX_XXXXXX.mp4 [-s [mm:]ss] [-t [mm:]ss] [-r rotation] [directory]"
 
-error () { printf "%s: %s\n" "${0##*/}" "$1" 1>&2; exit 1; }
-usage () { printf "$USAGE\n" "${0##*/}" 1>&2; exit 0; }
-
-media_converter="$(command -p -v ffmpeg)" || error "command not found -- ffmpeg"
+if ! media_converter="$(command -p -v ffmpeg)"; then
+    printf "%s: command not found -- ffmpeg\n" "${0##*/}" 1>&2
+    exit 1
+fi
 
 unset input rotate assume_yes start display_start end display_duration display_end
 while getopts :hi:s:t:r:y option; do
     case "$option" in
-        h) usage ;;
+        h) printf "$usage\n" "${0##*/}" 1>&2; exit 0 ;;
         i) input="$OPTARG" ;;
         s) start="$OPTARG" ;;
         t) end="$OPTARG" ;;
         r) rotate="$OPTARG" ;;
         y) assume_yes="-y" ;;
-        :) error "option requires an argument -- $OPTARG" ;;
-        ?) error "illegal argument -- $OPTARG" ;;
+        :) printf "%s: option requires an argument -- %c\n" "${0##*/}" "$OPTARG" 1>&2; exit 1 ;;
+        ?) printf "%s: illegal argument -- %c\n" "${0##*/}" "$OPTARG" 1>&2; exit 1 ;;
     esac
 done
 shift $(($OPTIND - 1))
 
-[ $# -le 1 ] || error "too many directory operands"
-[ $# -lt 1 ] && set -- '.'
+if [ $# -gt 1 ]; then
+    printf "%s: too many directory operands\n" "${0##*/}" 1>&2
+    exit 1
+elif [ $# -lt 1 ]; then
+    set -- '.'
+fi
 
-[ -n "${input+x}" ] || error "input file not specified"
-[ -f "$input" ] || error "file does not exist or is not a regular file -- $input"
-[ -r "$input" ] || error "unable to read file -- $input"
+if [ ! -n "${input+x}" ]; then
+    printf "%s: input file not specified\n" "${0##*/}" 1>&2
+    exit 1
+elif [ ! -f "$input" ]; then
+    printf "%s: file does not exist or is not a regular file -- %s\n" "${0##*/}" "$input" 1>&2
+    exit 1
+elif [ ! -r "$input" ]; then
+    printf "%s: unable to read file -- %s\n" "${0##*/}" "$input" 1>&2
+    exit 1
+fi
 
 case "${input##*/}" in
     VID_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9][0-9].mp4) ;;
-    *) error "invalid file operand" ;;
+    *) printf "%s: invalid file operand\n" "${0##*/}" 1>&2; exit 1 ;;
 esac
 
 case "$input" in
@@ -41,8 +52,13 @@ case "$input" in
     *) input_folder="." input_file="$input" ;;
 esac
 
-[ -d "$1" ] || error "directory does not exist or is not a directory"
-[ -w "$1" ] || error "permission denied for output directory"
+if [ ! -d "$1" ]; then
+    printf "%s: directory does not exist or is not a directory\n" "${0##*}" 1>&2
+    exit 1
+elif [ ! -w "$1" ]; then
+    printf "%s: permission denied for output directory\n" "${0##*}" 1>&2
+    exit 1
+fi
 
 case "$1" in
     /) output_folder="$1" ;;
@@ -51,7 +67,10 @@ esac
 
 input_string="$(cd "$input_folder" && pwd)"
 output_string="$(cd "$output_folder" && pwd)"
-[ "$input_string" != "$output_string" ] || error "input can not be in output directory"
+if [ "$input_string" = "$output_string" ]; then
+    printf "%s: input can not be in output directory\n" "${0##*/}" 1>&2
+    exit 1
+fi
 
 unset count prefix suffix year month day hour minute second
 
@@ -82,7 +101,7 @@ case "$second" in 0[0-9]) second="${second#0}" ;; esac
 if [ -n "${start+x}" ]; then
     case "$start" in
         [0-9]|[0-9][0-9]|[0-9][0-9]:[0-9][0-9]) ;;
-        *) error "invalid start argument (hint: <mm>:<ss> or <ss>)" ;;
+        *) printf "%s: invalid start operand\n" "${0##*/}" 1>&2; exit 1 ;;
     esac
 
     case "$start" in
@@ -112,7 +131,7 @@ fi
 if [ -n "${end+x}" ]; then
     case "$end" in
         [0-9]|[0-9][0-9]|[0-9][0-9]:[0-9][0-9]) ;;
-        *) error "invalid end argument (hint: <mm>:<ss> or <ss>)" ;;
+        *) printf "%s: invalid end operand\n" "${0##*/}" 1>&2; exit 1 ;;
     esac
 
     case "$end" in
@@ -136,7 +155,7 @@ fi
 if [ -n "${rotate+x}" ]; then
     case "$rotate" in
         [0-9]|[1-9][0-9]|[12][0-9][0-9]|3[0-5][0-9]|360) ;;
-        *) error "invalid rotation operand" ;;
+        *) printf "%s: invalid rotation operand\n" "${0##*/}" 1>&2; exit 1 ;;
     esac
     rotate="-display_rotation $rotate"
 fi
