update script

diff --git a/UbuntuInstall b/UbuntuInstall
--- a/UbuntuInstall
+++ b/UbuntuInstall
@@ -1,135 +1,128 @@
 #!/bin/sh
 
-set -ex
-EFFECTIVE_USER_ID="$(id -u)"
-test "$EFFECTIVE_USER_ID" -eq 0
+Error ()
+{
+	format="E: ${1}\\n"
+	shift 1
+	printf "$format" "$@" >&2
+	exit 1
+}
 
-command -v debootstrap
-command -v sfdisk
+effective_user_id="$(id -u 2> /dev/null)"
+effective_user_id="${effective_user_id:-1000}"
+test "$effective_user_id" -eq 0 || Error 'Permission denied'
 
-test $# -ge 1
-test $# -eq 2 && CODENAME="$2" || CODENAME="$(lsb_release -sc)"
+command -v debootstrap > /dev/null || Error 'Missing dependency -- debootstrap'
+command -v sfdisk > /dev/null || Error 'Missing dependency -- sfdisk'
+command -v debian-chroot > /dev/null || Error 'Missing dependency -- debian-chroot'
 
-DEV="$1"
-PART="${DEV}1"
+case $# in
+(0) Error 'Missing device operand' ;;
+(1) code_name="$(lsb_release -sc)" || Error 'Unable to get codename operand' ;;
+(*) Error 'Extra operands specified' ;;
+esac
 
-BUILD_DIR="/target"
-RESOLV_CONF="$BUILD_DIR/etc/resolv.conf"
+device="$1"
+partition="${device}1"
 
-sfdisk -f "$DEV" << EOF
+build_directory="/target"
+
+set -x
+set -e
+
+sfdisk -f "$device" << EOF
 2048,
 EOF
-sfdisk -f --part-type "$DEV" 1 83
-sfdisk -f -A "$DEV" 1
-mkfs.ext4 "$PART"
-test -d "$BUILD_DIR" || mkdir "$BUILD_DIR"; mount "$PART" "$BUILD_DIR"
+sfdisk -f --part-type "$device" 1 83
+sfdisk -f -A "$device" 1
+mkfs.ext4 "$partition"
 
-debootstrap --arch amd64 "$CODENAME" "$BUILD_DIR"
-
-mkdir -p "$BUILD_DIR/proc"; mount -t proc proc "$BUILD_DIR/proc"
-mkdir -p "$BUILD_DIR/sys"; mount -t sysfs sysfs "$BUILD_DIR/sys"
-mkdir -p "$BUILD_DIR/tmp"; mount -t tmpfs tmpfs "$BUILD_DIR/tmp"
-mkdir -p "$BUILD_DIR/run"; mount -t tmpfs run "$BUILD_DIR/run"
-if test -e "$RESOLV_CONF" || test -L "$RESOLV_CONF"; then
-  printf "%s\n" "nameserver 1.1.1.1" > "$BUILD_DIR/run/default-resolv.conf"
-  if test -L "$RESOLV_CONF"; then
-    RESOLV_CONF="$(readlink "$RESOLV_CONF")"
-    case "$RESOLV_CONF" in
-      /*) RESOLV_CONF="${BUILD_DIR}${RESOLV_CONF}" ;;
-      *) RESOLV_CONF="$BUILD_DIR/etc/$RESOLV_CONF" ;;
-    esac
-    test -f "$RESOLV_CONF" || install -Dm644 /dev/null "$RESOLV_CONF"
-  fi
-  mount --bind "$BUILD_DIR/run/default-resolv.conf" "$RESOLV_CONF"
-fi
-mkdir -p "$BUILD_DIR/dev"; mount --bind /dev "$BUILD_DIR/dev"
-
-DEVICE_LINE="$(blkid "$PART")"
-UUID="$(printf "%s\n" "$DEVICE_LINE" | sed 's/^.*[[:blank:]]\(UUID=\)"\([^"]\{1,\}\)"[[:blank:]].*$/\1\2/')"
-TYPE="$(printf "%s\n" "$DEVICE_LINE" | sed 's/^.*[[:blank:]]TYPE="\([^"]\{1,\}\)"[[:blank:]].*$/\1/')"
+mkdir -p "$build_directory"
+mount "$partiion" "$build_directory"
+debootstrap --arch amd64 "$code_name" "$build_directory"
 
 AWK='BEGIN{ printf "network:\n  version: 2\n  renderer: %s\n  ethernets:", "networkd" }
 /^[0-9]+/ && $2 != "lo:" { printf "\n    %s\n      dhcp4: true", $2 }'
-IP="$(ip link show)"
-FORMATED_IP="$(printf "%s\n" "$IP" | awk "$AWK")"
 
-mkdir -p "$BUILD_DIR/etc/netplan"
-cat > "$BUILD_DIR/etc/netplan/01-netcfg.yaml" << _EOF
-${FORMATED_IP}
-_EOF
+block_device_attributes="$(blkid --probe --output export "$PART")"
+unset UUID TYPE
+eval "$block_device_attributes"
+test -n "$UUID"
+test -n "$TYPE"
 
-cat > "$BUILD_DIR/etc/fstab" << _EOF
-${UUID} / ${TYPE} errors=remount-ro 0 1
-tmpfs /tmp tmpfs nosuid,nodev 0 0
-_EOF
+formated_ip="$(ip link show)"
+formated_ip="$(printf '%s' "$formated_ip" | awk "$AWK")"
 
-cat > "$BUILD_DIR/etc/hostname" << _EOF
-ubuntu
-_EOF
+fstab="$UUID / $TYPE errors=remount-ro 0 1
+tmpfs /tmp tmpfs nosuid,nodev 0 0"
+hostname="ubuntu"
+hosts="127.0.0.1    localhost
+127.0.1.1    $hostname
+"
 
-cat > "$BUILD_DIR/etc/hosts" << _EOF
-127.0.0.1    localhost
-127.0.1.1    ubuntu
-_EOF
+mkdir -p "$build_directory/etc/netplan"
+printf '%s\n' "$formated_ip" > "$build_directory/etc/netplan/01-netcfg.yaml"
+printf '%s\n' "$fstab" > "$build_directory/etc/fstab"
+printf '%s\n' "$hostname" > "$build_directory/etc/hostname"
+printf '%s\n' "$hosts" > "$build_directory/etc/hosts"
 
-mkdir -p "$BUILD_DIR/etc/apt"
-cat > "$BUILD_DIR/etc/apt/sources.list" << _EOF
+mkdir -p "$build_directory/etc/apt"; cat > "$build_directory/etc/apt/sources.list" << EndOfFile
 # See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
 # newer versions of the distribution.
-deb http://archive.ubuntu.com/ubuntu/ ${CODENAME} main restricted
-# deb-src http://archive.ubuntu.com/ubuntu/ ${CODENAME} main restricted
+deb http://archive.ubuntu.com/ubuntu/ ${code_name} main restricted
+# deb-src http://archive.ubuntu.com/ubuntu/ ${code_name} main restricted
 
 ## Major bug fix updates produced after the final release of the
 ## distribution.
-deb http://archive.ubuntu.com/ubuntu/ ${CODENAME}-updates main restricted
-# deb-src http://archive.ubuntu.com/ubuntu/ ${CODENAME}-updates main restricted
+deb http://archive.ubuntu.com/ubuntu/ ${code_name}-updates main restricted
+# deb-src http://archive.ubuntu.com/ubuntu/ ${code_name}-updates main restricted
 
 ## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
 ## team. Also, please note that software in universe WILL NOT receive any
 ## review or updates from the Ubuntu security team.
-deb http://archive.ubuntu.com/ubuntu/ ${CODENAME} universe
-# deb-src http://archive.ubuntu.com/ubuntu/ ${CODENAME} universe
-deb http://archive.ubuntu.com/ubuntu/ ${CODENAME}-updates universe
-# deb-src http://archive.ubuntu.com/ubuntu/ ${CODENAME}-updates universe
+deb http://archive.ubuntu.com/ubuntu/ ${code_name} universe
+# deb-src http://archive.ubuntu.com/ubuntu/ ${code_name} universe
+deb http://archive.ubuntu.com/ubuntu/ ${code_name}-updates universe
+# deb-src http://archive.ubuntu.com/ubuntu/ ${code_name}-updates universe
 
 ## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
 ## team, and may not be under a free licence. Please satisfy yourself as to
 ## your rights to use the software. Also, please note that software in
 ## multiverse WILL NOT receive any review or updates from the Ubuntu
 ## security team.
-deb http://archive.ubuntu.com/ubuntu/ ${CODENAME} multiverse
-# deb-src http://archive.ubuntu.com/ubuntu/ ${CODENAME} multiverse
-deb http://archive.ubuntu.com/ubuntu/ ${CODENAME}-updates multiverse
-# deb-src http://archive.ubuntu.com/ubuntu/ ${CODENAME}-updates multiverse
+deb http://archive.ubuntu.com/ubuntu/ ${code_name} multiverse
+# deb-src http://archive.ubuntu.com/ubuntu/ ${code_name} multiverse
+deb http://archive.ubuntu.com/ubuntu/ ${code_name}-updates multiverse
+# deb-src http://archive.ubuntu.com/ubuntu/ ${code_name}-updates multiverse
 
 ## N.B. software from this repository may not have been tested as
 ## extensively as that contained in the main release, although it includes
 ## newer versions of some applications which may provide useful features.
 ## Also, please note that software in backports WILL NOT receive any review
 ## or updates from the Ubuntu security team.
-deb http://archive.ubuntu.com/ubuntu/ ${CODENAME}-backports main restricted universe multiverse
-# deb-src http://archive.ubuntu.com/ubuntu/ ${CODENAME}-backports main restricted universe multiverse
+deb http://archive.ubuntu.com/ubuntu/ ${code_name}-backports main restricted universe multiverse
+# deb-src http://archive.ubuntu.com/ubuntu/ ${code_name}-backports main restricted universe multiverse
 
 ## Uncomment the following two lines to add software from Canonical's
 ## 'partner' repository.
 ## This software is not part of Ubuntu, but is offered by Canonical and the
 ## respective vendors as a service to Ubuntu users.
-# deb http://archive.canonical.com/ubuntu ${CODENAME} partner
-# deb-src http://archive.canonical.com/ubuntu ${CODENAME} partner
+# deb http://archive.canonical.com/ubuntu ${code_name} partner
+# deb-src http://archive.canonical.com/ubuntu ${code_name} partner
 
-deb http://security.ubuntu.com/ubuntu ${CODENAME}-security main restricted
-# deb-src http://security.ubuntu.com/ubuntu ${CODENAME}-security main restricted
-deb http://security.ubuntu.com/ubuntu ${CODENAME}-security universe
-# deb-src http://security.ubuntu.com/ubuntu ${CODENAME}-security universe
-deb http://security.ubuntu.com/ubuntu ${CODENAME}-security multiverse
-# deb-src http://security.ubuntu.com/ubuntu ${CODENAME}-security multiverse
-_EOF
+deb http://security.ubuntu.com/ubuntu ${code_name}-security main restricted
+# deb-src http://security.ubuntu.com/ubuntu ${code_name}-security main restricted
+deb http://security.ubuntu.com/ubuntu ${code_name}-security universe
+# deb-src http://security.ubuntu.com/ubuntu ${code_name}-security universe
+deb http://security.ubuntu.com/ubuntu ${code_name}-security multiverse
+# deb-src http://security.ubuntu.com/ubuntu ${code_name}-security multiverse
+EndOfFile
 
-LC_ALL=C chroot "$BUILD_DIR" /bin/sh -c '
-set -ex
+LC_ALL=C chroot "$build_directory" /bin/sh -c '
+set -x
+set -e
 apt-get update
 apt-get install -y linux-image-generic linux-headers-generic grub-pc build-essential
 apt-get dist-upgrade -y
 apt-get autoremove -y
-apt-get clean -y
-'
+apt-get clean -y'
